CREATE PROCEDURE `assets_tx_stat_procedure`(
	IN START_DATE DATETIME,
    IN END_DATE DATETIME
)
BEGIN
	DECLARE O_ROW_COUNT INT DEFAULT 0;

    SET O_ROW_COUNT = FOUND_ROWS();
    SELECT O_ROW_COUNT;
END